#
# ==============
# getlangcode.sk
# ==============
# getlangcode.sk is part of the SKYBLOCK.SK functions.
# ==============

# > Function - getlangcode:
# > Arguments:
# > <player>the player for which the language code is needed
# > Actions:
# > Returns the language code of the player.
function getlangcode(player:player) :: text:
  set {_uuid} to uuid of {_player}
  return {SK::lang::%{_uuid}%}

function getlang(id:text,langcode:text) :: text:
  return getconfigobject("%{_id}%-%{_langcode}%")
