#
# ==============
# blocks.yml
# ==============
# blocks.yml is part of the SKYBLOCK.SK configuration.
# ==============
version: 0.1
#
# > You can give the blocks here experience, if a player has the block on
# > his island, the island level will increase once it is calculated.
blocks:
- ACACIA_BOAT: 1
- ACACIA_BUTTON: 1
- ACACIA_DOOR: 2
- ACACIA_FENCE: 2
- ACACIA_FENCE_GATE: 1
- ACACIA_LEAVES: 1
- ACACIA_LOG: 3
- ACACIA_PLANKS: 1.5
- ACACIA_PRESSURE_PLATE: 1
- ACACIA_SAPLING: 1
- ACACIA_SLAB: 0.75
- ACACIA_STAIRS: 1
- ACACIA_TRAPDOOR: 1
- ACACIA_WOOD: 1
- ACTIVATOR_RAIL: 1
- AIR: 0
- ALLIUM: 1
- ANDESITE: 1
- ANVIL: 60
- APPLE: 1
- ARMOR_STAND: 1
- ARROW: 1
- ATTACHED_MELON_STEM: 1
- ATTACHED_PUMPKIN_STEM: 1
- AZURE_BLUET: 1
- BAKED_POTATO: 1
- BARRIER: 1
- BAT_SPAWN_EGG: 1
- BEACON: 1000
- BEDROCK: 0
- BEEF: 1
- BEETROOT: 1
- BEETROOT_SEEDS: 1
- BEETROOT_SOUP: 1
- BEETROOTS: 1
- BIRCH_BOAT: 1
- BIRCH_BUTTON: 1
- BIRCH_DOOR: 2
- BIRCH_FENCE: 2
- BIRCH_FENCE_GATE: 1
- BIRCH_LEAVES: 1
- BIRCH_LOG: 3
- BIRCH_PLANKS: 1.5
- BIRCH_PRESSURE_PLATE: 1
- BIRCH_SAPLING: 1
- BIRCH_SLAB: 1
- BIRCH_STAIRS: 1
- BIRCH_TRAPDOOR: 1
- BIRCH_WOOD: 1
- BLACK_BANNER: 10
- BLACK_BED: 3
- BLACK_CARPET: 1.5
- BLACK_CONCRETE: 1
- BLACK_CONCRETE_POWDER: 1
- BLACK_GLAZED_TERRACOTTA: 20
- BLACK_SHULKER_BOX: 1
- BLACK_STAINED_GLASS: 20
- BLACK_STAINED_GLASS_PANE: 7
- BLACK_TERRACOTTA: 20
- BLACK_WALL_BANNER: 10
- BLACK_WOOL: 2
- BLAZE_POWDER: 1
- BLAZE_ROD: 1
- BLAZE_SPAWN_EGG: 1
- BLUE_BANNER: 10
- BLUE_BED: 3
- BLUE_CARPET: 1.5
- BLUE_CONCRETE: 1
- BLUE_CONCRETE_POWDER: 1
- BLUE_GLAZED_TERRACOTTA: 20
- BLUE_ICE: 8
- BLUE_ORCHID: 1
- BLUE_SHULKER_BOX: 1
- BLUE_STAINED_GLASS: 20
- BLUE_STAINED_GLASS_PANE: 7
- BLUE_TERRACOTTA: 20
- BLUE_WALL_BANNER: 10
- BLUE_WOOL: 2
- BONE: 1
- BONE_BLOCK: 1
- BONE_MEAL: 1
- BOOK: 1
- BOOKSHELF: 10
- BOW: 1
- BOWL: 1
- BRAIN_CORAL: 1
- BRAIN_CORAL_BLOCK: 10
- BRAIN_CORAL_FAN: 1
- BRAIN_CORAL_WALL_FAN: 1
- BREAD: 1
- BREWING_STAND: 1
- BRICK: 1
- BRICK_SLAB: 1
- BRICK_STAIRS: 1
- BRICKS: 1
- BROWN_BANNER: 10
- BROWN_BED: 3
- BROWN_CARPET: 1.5
- BROWN_CONCRETE: 1
- BROWN_CONCRETE_POWDER: 1
- BROWN_GLAZED_TERRACOTTA: 20
- BROWN_MUSHROOM: 1
- BROWN_MUSHROOM_BLOCK: 1
- BROWN_SHULKER_BOX: 1
- BROWN_STAINED_GLASS: 20
- BROWN_STAINED_GLASS_PANE: 7
- BROWN_TERRACOTTA: 20
- BROWN_WALL_BANNER: 10
- BROWN_WOOL: 2
- BUBBLE_COLUMN: 1
- BUBBLE_CORAL: 1
- BUBBLE_CORAL_BLOCK: 10
- BUBBLE_CORAL_FAN: 1
- BUBBLE_CORAL_WALL_FAN: 1
- BUCKET: 1
- CACTUS: 1
- CACTUS_GREEN: 1
- CAKE: 1
- CARROT: 1
- CARROT_ON_A_STICK: 1
- CARROTS: 1
- CARVED_PUMPKIN: 1
- CAULDRON: 1
- CAVE_AIR: 1
- CAVE_SPIDER_SPAWN_EGG: 1
- CHAIN_COMMAND_BLOCK: 1
- CHAINMAIL_BOOTS: 1
- CHAINMAIL_CHESTPLATE: 1
- CHAINMAIL_HELMET: 1
- CHAINMAIL_LEGGINGS: 1
- CHARCOAL: 1
- CHEST: 2
- CHEST_MINECART: 1
- CHICKEN: 1
- CHICKEN_SPAWN_EGG: 1
- CHIPPED_ANVIL: 1
- CHISELED_QUARTZ_BLOCK: 1
- CHISELED_RED_SANDSTONE: 15
- CHISELED_SANDSTONE: 15
- CHISELED_STONE_BRICKS: 1
- CHORUS_FLOWER: 1
- CHORUS_FRUIT: 1
- CHORUS_PLANT: 1
- CLAY: 1
- CLAY_BALL: 1
- CLOCK: 1
- COAL: 1
- COAL_BLOCK: 1
- COAL_ORE: 1
- COARSE_DIRT: 1
- COBBLESTONE: 1
- COBBLESTONE_SLAB: 1
- COBBLESTONE_STAIRS: 1
- COBBLESTONE_WALL: 1
- COBWEB: 1
- COCOA: 1
- COCOA_BEANS: 1
- COD: 1
- COD_BUCKET: 1
- COD_SPAWN_EGG: 1
- COMMAND_BLOCK: 1
- COMMAND_BLOCK_MINECART: 1
- COMPARATOR: 1
- COMPASS: 1
- CONDUIT: 1
- COOKED_BEEF: 1
- COOKED_CHICKEN: 1
- COOKED_COD: 1
- COOKED_MUTTON: 1
- COOKED_PORKCHOP: 1
- COOKED_RABBIT: 1
- COOKED_SALMON: 1
- COOKIE: 1
- COW_SPAWN_EGG: 1
- CRACKED_STONE_BRICKS: 1
- CRAFTING_TABLE: 2
- CREEPER_HEAD: 1
- CREEPER_SPAWN_EGG: 1
- CREEPER_WALL_HEAD: 1
- CUT_RED_SANDSTONE: 15
- CUT_SANDSTONE: 15
- CYAN_BANNER: 10
- CYAN_BED: 3
- CYAN_CARPET: 1.5
- CYAN_CONCRETE: 1
- CYAN_CONCRETE_POWDER: 1
- CYAN_DYE: 1
- CYAN_GLAZED_TERRACOTTA: 20
- CYAN_SHULKER_BOX: 1
- CYAN_STAINED_GLASS: 20
- CYAN_STAINED_GLASS_PANE: 7
- CYAN_TERRACOTTA: 20
- CYAN_WALL_BANNER: 10
- CYAN_WOOL: 2
- DAMAGED_ANVIL: 1
- DANDELION: 1
- DANDELION_YELLOW: 1
- DARK_OAK_BOAT: 1
- DARK_OAK_BUTTON: 1
- DARK_OAK_DOOR: 2
- DARK_OAK_FENCE: 2
- DARK_OAK_FENCE_GATE: 1
- DARK_OAK_LEAVES: 1
- DARK_OAK_LOG: 3
- DARK_OAK_PLANKS: 1.5
- DARK_OAK_PRESSURE_PLATE: 1
- DARK_OAK_SAPLING: 1
- DARK_OAK_SLAB: 1
- DARK_OAK_STAIRS: 1
- DARK_OAK_TRAPDOOR: 1
- DARK_OAK_WOOD: 1
- DARK_PRISMARINE: 1
- DARK_PRISMARINE_SLAB: 1
- DARK_PRISMARINE_STAIRS: 1
- DAYLIGHT_DETECTOR: 1
- DEAD_BRAIN_CORAL: 1
- DEAD_BRAIN_CORAL_BLOCK: 10
- DEAD_BRAIN_CORAL_FAN: 1
- DEAD_BRAIN_CORAL_WALL_FAN: 1
- DEAD_BUBBLE_CORAL: 1
- DEAD_BUBBLE_CORAL_BLOCK: 10
- DEAD_BUBBLE_CORAL_FAN: 1
- DEAD_BUBBLE_CORAL_WALL_FAN: 1
- DEAD_BUSH: 1
- DEAD_FIRE_CORAL: 1
- DEAD_FIRE_CORAL_BLOCK: 10
- DEAD_FIRE_CORAL_FAN: 1
- DEAD_FIRE_CORAL_WALL_FAN: 1
- DEAD_HORN_CORAL: 1
- DEAD_HORN_CORAL_BLOCK: 10
- DEAD_HORN_CORAL_FAN: 1
- DEAD_HORN_CORAL_WALL_FAN: 1
- DEAD_TUBE_CORAL: 1
- DEAD_TUBE_CORAL_BLOCK: 10
- DEAD_TUBE_CORAL_FAN: 1
- DEAD_TUBE_CORAL_WALL_FAN: 1
- DEBUG_STICK: 1
- DETECTOR_RAIL: 1
- DIAMOND: 1
- DIAMOND_AXE: 1
- DIAMOND_BLOCK: 150
- DIAMOND_BOOTS: 1
- DIAMOND_CHESTPLATE: 1
- DIAMOND_HELMET: 1
- DIAMOND_HOE: 1
- DIAMOND_HORSE_ARMOR: 1
- DIAMOND_LEGGINGS: 1
- DIAMOND_ORE: 1
- DIAMOND_PICKAXE: 1
- DIAMOND_SHOVEL: 1
- DIAMOND_SWORD: 1
- DIORITE: 1
- DIRT: 20
- DISPENSER: 1
- DOLPHIN_SPAWN_EGG: 1
- DONKEY_SPAWN_EGG: 1
- DRAGON_BREATH: 1
- DRAGON_EGG: 1
- DRAGON_HEAD: 1
- DRAGON_WALL_HEAD: 1
- DRIED_KELP: 1
- DRIED_KELP_BLOCK: 1
- DROPPER: 1
- DROWNED_SPAWN_EGG: 1
- EGG: 1
- ELDER_GUARDIAN_SPAWN_EGG: 1
- ELYTRA: 1
- EMERALD: 1
- EMERALD_BLOCK: 75
- EMERALD_ORE: 1
- ENCHANTED_BOOK: 1
- ENCHANTED_GOLDEN_APPLE: 1
- ENCHANTING_TABLE: 250
- END_CRYSTAL: 1
- END_GATEWAY: 1
- END_PORTAL: 1
- END_PORTAL_FRAME: 1
- END_ROD: 1
- END_STONE: 1
- END_STONE_BRICKS: 1
- ENDER_CHEST: 150
- ENDER_EYE: 1
- ENDER_PEARL: 1
- ENDERMAN_SPAWN_EGG: 1
- ENDERMITE_SPAWN_EGG: 1
- EVOKER_SPAWN_EGG: 1
- EXPERIENCE_BOTTLE: 1
- FARMLAND: 20
- FEATHER: 1
- FERMENTED_SPIDER_EYE: 1
- FERN: 1
- FILLED_MAP: 1
- FIRE: 1
- FIRE_CHARGE: 1
- FIRE_CORAL: 1
- FIRE_CORAL_BLOCK: 10
- FIRE_CORAL_FAN: 1
- FIRE_CORAL_WALL_FAN: 1
- FIREWORK_ROCKET: 1
- FIREWORK_STAR: 1
- FISHING_ROD: 1
- FLINT: 1
- FLINT_AND_STEEL: 1
- FLOWER_POT: 20
- FROSTED_ICE: 1
- FURNACE: 6
- FURNACE_MINECART: 1
- GHAST_SPAWN_EGG: 1
- GHAST_TEAR: 1
- GLASS: 1
- GLASS_BOTTLE: 1
- GLASS_PANE: 7
- GLISTERING_MELON_SLICE: 1
- GLOWSTONE: 4
- GLOWSTONE_DUST: 1
- GOLD_BLOCK: 50
- GOLD_INGOT: 1
- GOLD_NUGGET: 1
- GOLD_ORE: 1
- GOLDEN_APPLE: 1
- GOLDEN_AXE: 1
- GOLDEN_BOOTS: 1
- GOLDEN_CARROT: 1
- GOLDEN_CHESTPLATE: 1
- GOLDEN_HELMET: 1
- GOLDEN_HOE: 1
- GOLDEN_HORSE_ARMOR: 1
- GOLDEN_LEGGINGS: 1
- GOLDEN_PICKAXE: 1
- GOLDEN_SHOVEL: 1
- GOLDEN_SWORD: 1
- GRANITE: 1
- GRASS: 1
- GRASS_BLOCK: 20
- GRASS_PATH: 1
- GRAVEL: 1
- GRAY_BANNER: 10
- GRAY_BED: 3
- GRAY_CARPET: 1.5
- GRAY_CONCRETE: 1
- GRAY_CONCRETE_POWDER: 1
- GRAY_DYE: 1
- GRAY_GLAZED_TERRACOTTA: 20
- GRAY_SHULKER_BOX: 1
- GRAY_STAINED_GLASS: 20
- GRAY_STAINED_GLASS_PANE: 7
- GRAY_TERRACOTTA: 20
- GRAY_WALL_BANNER: 10
- GRAY_WOOL: 2
- GREEN_BANNER: 10
- GREEN_BED: 3
- GREEN_CARPET: 1.5
- GREEN_CONCRETE: 1
- GREEN_CONCRETE_POWDER: 1
- GREEN_GLAZED_TERRACOTTA: 20
- GREEN_SHULKER_BOX: 1
- GREEN_STAINED_GLASS: 20
- GREEN_STAINED_GLASS_PANE: 7
- GREEN_TERRACOTTA: 20
- GREEN_WALL_BANNER: 10
- GREEN_WOOL: 2
- GUARDIAN_SPAWN_EGG: 1
- GUNPOWDER: 1
- HAY_BLOCK: 1
- HEART_OF_THE_SEA: 1
- HEAVY_WEIGHTED_PRESSURE_PLATE: 1
- HOPPER: 4
- HOPPER_MINECART: 1
- HORN_CORAL: 1
- HORN_CORAL_BLOCK: 10
- HORN_CORAL_FAN: 1
- HORN_CORAL_WALL_FAN: 1
- HORSE_SPAWN_EGG: 1
- HUSK_SPAWN_EGG: 1
- ICE: 2
- INFESTED_CHISELED_STONE_BRICKS: 1
- INFESTED_COBBLESTONE: 1
- INFESTED_CRACKED_STONE_BRICKS: 1
- INFESTED_MOSSY_STONE_BRICKS: 1
- INFESTED_STONE: 1
- INFESTED_STONE_BRICKS: 1
- INK_SAC: 1
- IRON_AXE: 1
- IRON_BARS: 1
- IRON_BLOCK: 20
- IRON_BOOTS: 1
- IRON_CHESTPLATE: 1
- IRON_DOOR: 2
- IRON_HELMET: 1
- IRON_HOE: 1
- IRON_HORSE_ARMOR: 1
- IRON_INGOT: 1
- IRON_LEGGINGS: 1
- IRON_NUGGET: 1
- IRON_ORE: 1
- IRON_PICKAXE: 1
- IRON_SHOVEL: 1
- IRON_SWORD: 1
- IRON_TRAPDOOR: 1
- ITEM_FRAME: 1
- JACK_O_LANTERN: 1
- JUKEBOX: 15
- JUNGLE_BOAT: 1
- JUNGLE_BUTTON: 1
- JUNGLE_DOOR: 2
- JUNGLE_FENCE: 2
- JUNGLE_FENCE_GATE: 1
- JUNGLE_LEAVES: 1
- JUNGLE_LOG: 3
- JUNGLE_PLANKS: 1.5
- JUNGLE_PRESSURE_PLATE: 1
- JUNGLE_SAPLING: 1
- JUNGLE_SLAB: 1
- JUNGLE_STAIRS: 1
- JUNGLE_TRAPDOOR: 1
- JUNGLE_WOOD: 1
- KELP: 0.5
- KELP_PLANT: 1
- KNOWLEDGE_BOOK: 1
- LADDER: 1
- LAPIS_BLOCK: 50
- LAPIS_LAZULI: 1
- LAPIS_ORE: 1
- LARGE_FERN: 1
- LAVA: 1
- LAVA_BUCKET: 1
- LEAD: 1
- LEATHER: 1
- LEATHER_BOOTS: 1
- LEATHER_CHESTPLATE: 1
- LEATHER_HELMET: 1
- LEATHER_LEGGINGS: 1
- LEVER: 1
- LIGHT_BLUE_BANNER: 10
- LIGHT_BLUE_BED: 3
- LIGHT_BLUE_CARPET: 1.5
- LIGHT_BLUE_CONCRETE: 1
- LIGHT_BLUE_CONCRETE_POWDER: 1
- LIGHT_BLUE_DYE: 1
- LIGHT_BLUE_GLAZED_TERRACOTTA: 20
- LIGHT_BLUE_SHULKER_BOX: 1
- LIGHT_BLUE_STAINED_GLASS: 20
- LIGHT_BLUE_STAINED_GLASS_PANE: 7
- LIGHT_BLUE_TERRACOTTA: 20
- LIGHT_BLUE_WALL_BANNER: 10
- LIGHT_BLUE_WOOL: 2
- LIGHT_GRAY_BANNER: 10
- LIGHT_GRAY_BED: 3
- LIGHT_GRAY_CARPET: 1.5
- LIGHT_GRAY_CONCRETE: 1
- LIGHT_GRAY_CONCRETE_POWDER: 1
- LIGHT_GRAY_DYE: 1
- LIGHT_GRAY_GLAZED_TERRACOTTA: 20
- LIGHT_GRAY_SHULKER_BOX: 1
- LIGHT_GRAY_STAINED_GLASS: 20
- LIGHT_GRAY_STAINED_GLASS_PANE: 7
- LIGHT_GRAY_TERRACOTTA: 20
- LIGHT_GRAY_WALL_BANNER: 10
- LIGHT_GRAY_WOOL: 2
- LIGHT_WEIGHTED_PRESSURE_PLATE: 1
- LILAC: 1
- LILY_PAD: 1
- LIME_BANNER: 10
- LIME_BED: 3
- LIME_CARPET: 1.5
- LIME_CONCRETE: 1
- LIME_CONCRETE_POWDER: 1
- LIME_DYE: 1
- LIME_GLAZED_TERRACOTTA: 20
- LIME_SHULKER_BOX: 1
- LIME_STAINED_GLASS: 20
- LIME_STAINED_GLASS_PANE: 7
- LIME_TERRACOTTA: 20
- LIME_WALL_BANNER: 10
- LIME_WOOL: 2
- LINGERING_POTION: 1
- LLAMA_SPAWN_EGG: 1
- MAGENTA_BANNER: 10
- MAGENTA_BED: 3
- MAGENTA_CARPET: 1.5
- MAGENTA_CONCRETE: 1
- MAGENTA_CONCRETE_POWDER: 1
- MAGENTA_DYE: 1
- MAGENTA_GLAZED_TERRACOTTA: 20
- MAGENTA_SHULKER_BOX: 1
- MAGENTA_STAINED_GLASS: 20
- MAGENTA_STAINED_GLASS_PANE: 7
- MAGENTA_TERRACOTTA: 20
- MAGENTA_WALL_BANNER: 10
- MAGENTA_WOOL: 2
- MAGMA_BLOCK: 1
- MAGMA_CREAM: 1
- MAGMA_CUBE_SPAWN_EGG: 1
- MAP: 1
- MELON: 2
- MELON_SEEDS: 1
- MELON_SLICE: 1
- MELON_STEM: 2
- MILK_BUCKET: 1
- MINECART: 1
- MOOSHROOM_SPAWN_EGG: 1
- MOSSY_COBBLESTONE: 1
- MOSSY_COBBLESTONE_WALL: 1
- MOSSY_STONE_BRICKS: 1
- MULE_SPAWN_EGG: 1
- MUSHROOM_STEM: 1
- MUSHROOM_STEW: 1
- MUSIC_DISC_11: 1
- MUSIC_DISC_13: 1
- MUSIC_DISC_BLOCKS: 1
- MUSIC_DISC_CAT: 1
- MUSIC_DISC_CHIRP: 1
- MUSIC_DISC_FAR: 1
- MUSIC_DISC_MALL: 1
- MUSIC_DISC_MELLOHI: 1
- MUSIC_DISC_STAL: 1
- MUSIC_DISC_STRAD: 1
- MUSIC_DISC_WAIT: 1
- MUSIC_DISC_WARD: 1
- MUTTON: 1
- MYCELIUM: 1
- NAME_TAG: 1
- NAUTILUS_SHELL: 1
- NETHER_BRICK: 4
- NETHER_BRICK_FENCE: 2
- NETHER_BRICK_SLAB: 1
- NETHER_BRICK_STAIRS: 1
- NETHER_BRICKS: 1
- NETHER_PORTAL: 0.25
- NETHER_QUARTZ_ORE: 1
- NETHER_STAR: 500
- NETHER_WART: 1
- NETHER_WART_BLOCK: 4
- NETHERRACK: 0.5
- NOTE_BLOCK: 20
- OAK_BOAT: 1
- OAK_BUTTON: 1
- OAK_DOOR: 2
- OAK_FENCE: 2
- OAK_FENCE_GATE: 1
- OAK_LEAVES: 1
- OAK_LOG: 3
- OAK_PLANKS: 1.5
- OAK_PRESSURE_PLATE: 1
- OAK_SAPLING: 2
- OAK_SLAB: 1
- OAK_STAIRS: 1
- OAK_TRAPDOOR: 1
- OAK_WOOD: 1
- OBSERVER: 1
- OBSIDIAN: 300
- OCELOT_SPAWN_EGG: 1
- ORANGE_BANNER: 10
- ORANGE_BED: 3
- ORANGE_CARPET: 1.5
- ORANGE_CONCRETE: 1
- ORANGE_CONCRETE_POWDER: 1
- ORANGE_DYE: 1
- ORANGE_GLAZED_TERRACOTTA: 20
- ORANGE_SHULKER_BOX: 1
- ORANGE_STAINED_GLASS: 20
- ORANGE_STAINED_GLASS_PANE: 7
- ORANGE_TERRACOTTA: 20
- ORANGE_TULIP: 1
- ORANGE_WALL_BANNER: 10
- ORANGE_WOOL: 2
- OXEYE_DAISY: 1
- PACKED_ICE: 5
- PAINTING: 1
- PAPER: 1
- PARROT_SPAWN_EGG: 1
- PEONY: 1
- PETRIFIED_OAK_SLAB: 1
- PHANTOM_MEMBRANE: 1
- PHANTOM_SPAWN_EGG: 1
- PIG_SPAWN_EGG: 1
- PINK_BANNER: 10
- PINK_BED: 3
- PINK_CARPET: 1.5
- PINK_CONCRETE: 1
- PINK_CONCRETE_POWDER: 1
- PINK_DYE: 1
- PINK_GLAZED_TERRACOTTA: 20
- PINK_SHULKER_BOX: 1
- PINK_STAINED_GLASS: 20
- PINK_STAINED_GLASS_PANE: 7
- PINK_TERRACOTTA: 20
- PINK_TULIP: 1
- PINK_WALL_BANNER: 10
- PINK_WOOL: 2
- PISTON: 4
- PISTON_HEADHead: 1
- PLAYER_HEAD: 1
- PLAYER_WALL_HEAD: 1
- PODZOL: 1
- POISONOUS_POTATO: 1
- POLAR_BEAR_SPAWN_EGG: 1
- POLISHED_ANDESITE: 1
- POLISHED_DIORITE: 1
- POLISHED_GRANITE: 1
- POPPED_CHORUS_FRUIT: 1
- POPPY: 1
- PORKCHOP: 1
- POTATO: 1
- POTATOES: 1
- POTION: 1
- POTTED_ACACIA_SAPLING: 5
- POTTED_ALLIUM: 5
- POTTED_AZURE_BLUET: 5
- POTTED_BIRCH_SAPLING: 5
- POTTED_BLUE_ORCHID: 5
- POTTED_BROWN_MUSHROOM: 5
- POTTED_CACTUS: 5
- POTTED_DANDELION: 5
- POTTED_DARK_OAK_SAPLING: 5
- POTTED_DEAD_BUSH: 5
- POTTED_FERN: 5
- POTTED_JUNGLE_SAPLING: 5
- POTTED_OAK_SAPLING: 5
- POTTED_ORANGE_TULIP: 5
- POTTED_OXEYE_DAISY: 5
- POTTED_PINK_TULIP: 5
- POTTED_POPPY: 5
- POTTED_RED_MUSHROOM: 5
- POTTED_RED_TULIP: 5
- POTTED_SPRUCE_SAPLING: 5
- POTTED_WHITE_TULIP: 5
- POWERED_RAIL: 3
- PRISMARINE: 10
- PRISMARINE_BRICK_SLAB: 5
- PRISMARINE_BRICK_STAIRS: 7
- PRISMARINE_BRICKS: 15
- PRISMARINE_CRYSTALS: 1
- PRISMARINE_SHARD: 1
- PRISMARINE_SLAB: 5
- PRISMARINE_STAIRS: 7
- PUFFERFISH: 1
- PUFFERFISH_BUCKET: 1
- PUFFERFISH_SPAWN_EGG: 1
- PUMPKIN: 2
- PUMPKIN_PIE: 1
- PUMPKIN_SEEDS: 1
- PUMPKIN_STEM: 2
- PURPLE_BANNER: 10
- PURPLE_BED: 3
- PURPLE_CARPET: 1.5
- PURPLE_CONCRETE: 1
- PURPLE_CONCRETE_POWDER: 1
- PURPLE_DYE: 1
- PURPLE_GLAZED_TERRACOTTA: 20
- PURPLE_SHULKER_BOX: 1
- PURPLE_STAINED_GLASS: 20
- PURPLE_STAINED_GLASS_PANE: 7
- PURPLE_TERRACOTTA: 20
- PURPLE_WALL_BANNER: 10
- PURPLE_WOOL: 2
- PURPUR_BLOCK: 1
- PURPUR_PILLAR: 1
- PURPUR_SLAB: 1
- PURPUR_STAIRS: 1
- QUARTZ: 1
- QUARTZ_BLOCK: 25
- QUARTZ_PILLAR: 25
- QUARTZ_SLAB: 10
- QUARTZ_STAIRS: 10
- RABBIT: 1
- RABBIT_FOOT: 1
- RABBIT_HIDE: 1
- RABBIT_SPAWN_EGG: 1
- RABBIT_STEW: 1
- RAIL: 1
- RED_BANNER: 10
- RED_BED: 3
- RED_CARPET: 1.5
- RED_CONCRETE: 1
- RED_CONCRETE_POWDER: 1
- RED_GLAZED_TERRACOTTA: 20
- RED_MUSHROOM: 1
- RED_MUSHROOM_BLOCK: 1
- RED_NETHER_BRICKS: 1
- RED_SAND: 5
- RED_SANDSTONE: 15
- RED_SANDSTONE_SLAB: 1
- RED_SANDSTONE_STAIRS: 1
- RED_SHULKER_BOX: 1
- RED_STAINED_GLASS: 20
- RED_STAINED_GLASS_PANE: 7
- RED_TERRACOTTA: 20
- RED_TULIP: 1
- RED_WALL_BANNER: 10
- RED_WOOL: 2
- REDSTONE: 2
- REDSTONE_BLOCK: 30
- REDSTONE_LAMP: 5
- REDSTONE_ORE: 1
- REDSTONE_TORCH: 2
- REDSTONE_WALL_TORCH: 2
- REDSTONE_WIRE: 1
- REPEATER: 3
- REPEATING_COMMAND_BLOCK: 1
- ROSE_BUSH: 2
- ROSE_RED: 1
- ROTTEN_FLESH: 1
- SADDLE: 1
- SALMON: 1
- SALMON_BUCKET: 1
- SALMON_SPAWN_EGG: 1
- SAND: 5
- SANDSTONE: 150
- SANDSTONE_SLAB: 5
- SANDSTONE_STAIRS: 5
- SCUTE: 1
- SEA_LANTERN: 1
- SEA_PICKLE: 1
- SEAGRASS: 1
- SHEARS: 1
- SHEEP_SPAWN_EGG: 1
- SHIELD: 1
- SHULKER_BOX: 1
- SHULKER_SHELL: 1
- SHULKER_SPAWN_EGG: 1
- SIGN: 5
- SILVERFISH_SPAWN_EGG: 1
- SKELETON_HORSE_SPAWN_EGG: 1
- SKELETON_SKULL: 1
- SKELETON_SPAWN_EGG: 1
- SKELETON_WALL_SKULL: 1
- SLIME_BALL: 1
- SLIME_BLOCK: 1
- SLIME_SPAWN_EGG: 1
- SMOOTH_QUARTZ: 15
- SMOOTH_RED_SANDSTONE: 150
- SMOOTH_SANDSTONE: 150
- SMOOTH_STONE: 2
- SNOW: 1
- SNOW_BLOCK: 1
- SNOWBALL: 1
- SOUL_SAND: 5
- SPAWNER: 1
- SPECTRAL_ARROW: 1
- SPIDER_EYE: 1
- SPIDER_SPAWN_EGG: 1
- SPLASH_POTION: 1
- SPONGE: 1
- SPRUCE_BOAT: 1
- SPRUCE_BUTTON: 1
- SPRUCE_DOOR: 2
- SPRUCE_FENCE: 2
- SPRUCE_FENCE_GATE: 1
- SPRUCE_LEAVES: 1
- SPRUCE_LOG: 3
- SPRUCE_PLANKS: 1.5
- SPRUCE_PRESSURE_PLATE: 1
- SPRUCE_SAPLING: 1
- SPRUCE_SLAB: 1
- SPRUCE_STAIRS: 1
- SPRUCE_TRAPDOOR: 1
- SPRUCE_WOOD: 1
- SQUID_SPAWN_EGG: 1
- STICK: 1
- STICKY_PISTON: 4
- STONE: 1
- STONE_AXE: 1
- STONE_BRICK_SLAB: 0.75
- STONE_BRICK_STAIRS: 1
- STONE_BRICKS: 1.5
- STONE_BUTTON: 1
- STONE_HOE: 1
- STONE_PICKAXE: 1
- STONE_PRESSURE_PLATE: 1
- STONE_SHOVEL: 1
- STONE_SLAB: 1
- STONE_SWORD: 1
- STRAY_SPAWN_EGG: 1
- STRING: 1
- STRIPPED_ACACIA_LOG: 3
- STRIPPED_ACACIA_WOOD: 1.5
- STRIPPED_BIRCH_LOG: 3
- STRIPPED_BIRCH_WOOD: 1.5
- STRIPPED_DARK_OAK_LOG: 3
- STRIPPED_DARK_OAK_WOOD: 1.5
- STRIPPED_JUNGLE_LOG: 3
- STRIPPED_JUNGLE_WOOD: 1.5
- STRIPPED_OAK_LOG: 3
- STRIPPED_OAK_WOOD: 1.5
- STRIPPED_SPRUCE_LOG: 3
- STRIPPED_SPRUCE_WOOD: 1.5
- STRUCTURE_BLOCK: 0
- STRUCTURE_VOID: 0
- SUGAR: 1
- SUGAR_CANE: 0.5
- SUNFLOWER: 1
- TALL_GRASS: 1
- TALL_SEAGRASS: 1
- TERRACOTTA: 1
- TIPPED_ARROW: 1
- TNT: 1
- TNT_MINECART: 1
- TORCH: 1
- TOTEM_OF_UNDYING: 1
- TRAPPED_CHEST: 5
- TRIDENT: 1
- TRIPWIRE: 1
- TRIPWIRE_HOOK: 1
- TROPICAL_FISH: 1
- TROPICAL_FISH_BUCKET: 1
- TROPICAL_FISH_SPAWN_EGG: 1
- TUBE_CORAL: 1
- TUBE_CORAL_BLOCK: 10
- TUBE_CORAL_FAN: 1
- TUBE_CORAL_WALL_FAN: 1
- TURTLE_EGG: 1
- TURTLE_HELMET: 1
- TURTLE_SPAWN_EGG: 1
- VEX_SPAWN_EGG: 1
- VILLAGER_SPAWN_EGG: 1
- VINDICATOR_SPAWN_EGG: 1
- VINE: 1
- VOID_AIR: 1
- WALL_SIGN: 5
- WALL_TORCH: 2
- WATER: 0
- WATER_BUCKET: 1
- WET_SPONGE: 1
- WHEAT: 1
- WHEAT_SEEDS: 1
- WHITE_BANNER: 10
- WHITE_BED: 3
- WHITE_CARPET: 1.5
- WHITE_CONCRETE: 1
- WHITE_CONCRETE_POWDER: 1
- WHITE_GLAZED_TERRACOTTA: 20
- WHITE_SHULKER_BOX: 1
- WHITE_STAINED_GLASS: 20
- WHITE_STAINED_GLASS_PANE: 7
- WHITE_TERRACOTTA: 20
- WHITE_TULIP: 1
- WHITE_WALL_BANNER: 10
- WHITE_WOOL: 2
- WITCH_SPAWN_EGG: 1
- WITHER_SKELETON_SKULL: 1
- WITHER_SKELETON_SPAWN_EGG: 1
- WITHER_SKELETON_WALL_SKULL: 1
- WOLF_SPAWN_EGG: 1
- WOODEN_AXE: 1
- WOODEN_HOE: 1
- WOODEN_PICKAXE: 1
- WOODEN_SHOVEL: 1
- WOODEN_SWORD: 1
- WRITABLE_BOOK: 1
- WRITTEN_BOOK: 1
- YELLOW_BANNER: 10
- YELLOW_BED: 3
- YELLOW_CARPET: 1.5
- YELLOW_CONCRETE: 1
- YELLOW_CONCRETE_POWDER: 1
- YELLOW_GLAZED_TERRACOTTA: 20
- YELLOW_SHULKER_BOX: 1
- YELLOW_STAINED_GLASS: 20
- YELLOW_STAINED_GLASS_PANE: 7
- YELLOW_TERRACOTTA: 20
- YELLOW_WALL_BANNER: 10
- YELLOW_WOOL: 2
- ZOMBIE_HEAD: 1
- ZOMBIE_HORSE_SPAWN_EGG: 1
- ZOMBIE_PIGMAN_SPAWN_EGG: 1
- ZOMBIE_SPAWN_EGG: 1
- ZOMBIE_VILLAGER_SPAWN_EGG: 1
- ZOMBIE_WALL_HEAD: 1
