#
# ==============
# challenges.yml
# ==============
# challenges.yml is part of the SKYBLOCK.SK configuration.
# ==============

#
# > Define the xp threshold for every challenge level, the higher, the harder
# > it gets to climb up the levels. To have everything unlocked at the beginning,
# > set all thresholds to 0.
threshold:
- 1: 0
- 2: 250
- 3: 500
- 4: 2500
- 5: 5000

repeatmodifier:
  #
  # > Toggle the repeat bonus modifier from on [true] and off [false].
- enabled: true
  #
  # > Set here the amount in percent, how much the repeats should be increased per level.
  # > 10 means 10% per defined 500 xp + difficulty modifier per level. 
- repeatincrease: 10
  #
  # > Set the amount of xp needed for a increase of the repeats.
- xprepeatincrease: 500
  #
  # > Increase the amount of the needed experience to increase the repeats
  # > with a predefined difficulty modifier which gets harder every time the
  # > increasement has happened.
- difficulty: 25
  #
  # > Set the item which should appear to display the repeat modifier statistics.
- item: "magenta glazed terracotta"

#
# > Define the challenges. You can edit the already existing challenges as you want or add new ones.
challenges:
- 1_1_needed: "64-cactus"
- 1_1_reward: "15-xp,2-sand"
- 1_1_repeatreward: "1-xp,1-sand"
- 1_1_item: "sand block"
- 1_1_repeat: true
- 1_1_repeatsperday: 150
- 1_1_customfunction: ""
- 1_1_customreward: ""

- 1_2_needed: "48-cobblestone,16-gunpowder"
- 1_2_reward: "1-xp,16-gravel"
- 1_2_repeatreward: "1-xp,8-gravel,2-soul sand"
- 1_2_item: "gravel block"
- 1_2_repeat: true
- 1_2_repeatsperday: 15

- 1_3_needed: "64-oak leaves,32-cobblestone,32-stone brick"
- 1_3_reward: "1-xp,16-mossy cobblestone,16-mossy stone brick"
- 1_3_repeatreward: "1-xp,4-mossy cobblestone,4-mossy stone brick"
- 1_3_item: "mossy stone brick"
- 1_3_repeat: true
- 1_3_repeatsperday: 10
- 1_3_customfunction: ""

- 1_4_needed: "6-apple"
- 1_4_reward: "15-xp,2-oak sapling,2-spruce sapling,2-birch sapling,2-jungle sapling,2-acacia sapling,4-dark oak sapling"
- 1_4_repeatreward: "5-xp,1-oak sapling,1-spruce sapling,1-birch sapling,1-jungle sapling,1-acacia sapling,2-dark oak sapling"
- 1_4_item: "apple"
- 1_4_repeat: true
- 1_4_repeatsperday: 5

- 1_5_needed: "64-sugar cane"
- 1_5_reward: "10-xp,20-clay block"
- 1_5_repeatreward: "1-xp,5-clay block"
- 1_5_item: "clay block"
- 1_5_repeat: true
- 1_5_repeatsperday: 45

- 1_6_needed: "128-melon slice"
- 1_6_reward: "15-xp,3-sand"
- 1_6_repeatreward: "1-xp,1-sand"
- 1_6_item: "melon slice"
- 1_6_repeat: true
- 1_6_repeatsperday: 30

- 1_7_needed: "64-pumpkin"
- 1_7_reward: "20-xp,3-red sand"
- 1_7_repeatreward: "1-xp,1-red sand"
- 1_7_item: "pumpkin"
- 1_7_repeat: true
- 1_7_repeatsperday: 15

- 2_1_needed: "16-oak log,16-spruce log,16-birch log,16-jungle log,16-acacia log,16-dark oak log"
- 2_1_reward: "20-xp,16-redstone dust,5-iron ore,1-wolf spawn egg"
- 2_1_repeatreward: "1-xp,3-redstone dust,1-iron ore,1-nether wart item"
- 2_1_item: "oak log"
- 2_1_repeat: true
- 2_1_repeatsperday: 5

- 2_2_needed: "3-diamond,2-iron ingot"
- 2_2_reward: "150-xp,3-dirt"
- 2_2_repeatreward: "10-xp,1-dirt"
- 2_2_item: "dirt"
- 2_2_repeat: true
- 2_2_repeatsperday: 5

- 2_3_needed: "64-nether wart item"
- 2_3_reward: "45-xp,32-netherrack"
- 2_3_repeatreward: "3-xp,1-magma block,18-netherrack"
- 2_3_item: "netherrack"
- 2_3_repeat: true
- 2_3_repeatsperday: 30

- 2_4_needed: "64-red mushroom,64-brown mushroom"
- 2_4_reward: "40-xp,1-mycelium"
- 2_4_repeatreward: "15-xp,1-mycelium"
- 2_4_item: "mycelium"
- 2_4_repeat: true
- 2_4_repeatsperday: 5

- 2_5_needed: "128-cookie,1-milk bucket"
- 2_5_reward: "25-xp,64-jungle log,1-bucket"
- 2_5_repeatreward: "3-xp,32-jungle log,1-bucket"
- 2_5_item: "cookie"
- 2_5_repeat: true
- 2_5_repeatsperday: 5

- 2_6_needed: "64-wheat seeds,64-pumpkin seeds,64-melon seeds,64-beetroot seeds"
- 2_6_reward: "70-xp,4-peony,4-rose bush,4-lilac,4-sunflower,4-brown mushroom,4-red mushroom"
- 2_6_repeatreward: "3-xp,1-peony,1-rose bush,1-lilac,1-sunflower,1-brown mushroom,1-red mushroom"
- 2_6_item: "peony"
- 2_6_repeat: true
- 2_6_repeatsperday: 5

- 2_7_needed: "12-pumpkin pie,2-cake,16-bread,32-cookie"
- 2_7_reward: "10-xp,2-gold ore,2-iron ore"
- 2_7_repeatreward: "2-xp,1-iron ore"
- 2_7_item: "pumpkin pie"
- 2_7_repeat: true
- 2_7_repeatsperday: 5

- 3_1_needed: "128-cobblestone"
- 3_1_reward: "20-xp,2-iron ore"
- 3_1_repeatreward: "1-xp,1-iron ore"
- 3_1_item: "cobblestone"
- 3_1_repeat: true
- 3_1_repeatsperday: 15

- 3_2_needed: "64-raw cod"
- 3_2_reward: "150-xp,4-sea pickle,4-kelp,2-nautilus shell"
- 3_2_repeatreward: "10-xp,2-sea pickle,2-kelp,1-nautilus shell"
- 3_2_item: "raw cod"
- 3_2_repeat: true
- 3_2_repeatsperday: 15

- 3_3_needed: "9-living tube coral plant,9-living brain coral plant,9-living bubble coral plant,9-living fire coral plant,9-living horn coral plant"
- 3_3_reward: "150-xp,2-living tube coral block,2-living brain coral block,2-living bubble coral block,2-living fire coral block,2-living horn coral block"
- 3_3_repeatreward: "10-xp,1-living tube coral block,1-living brain coral block,1-living bubble coral block,1-living fire coral block,1-living horn coral block"
- 3_3_item: "living pink coral block"
- 3_3_repeat: true
- 3_3_repeatsperday: 20

- 3_4_needed: "64-living tube coral block,64-living brain coral block,64-living bubble coral block,64-living fire coral block,64-living horn coral block"
- 3_4_reward: "150-xp,1-sponge,1-heart of the sea"
- 3_4_repeatreward: "10-xp,1-sponge,1-heart of the sea"
- 3_4_item: "heart of the sea"
- 3_4_repeat: true
- 3_4_repeatsperday: 5

- 3_5_needed: "128-ender pearl"
- 3_5_reward: "75-xp,2-shulker shell"
- 3_5_repeatreward: "10-xp,1-shulker shell"
- 3_5_item: "ender pearl"
- 3_5_repeat: true
- 3_5_repeatsperday: 5

- 3_6_needed: "16-emerald"
- 3_6_reward: "35-xp,32-bottle o' enchanting"
- 3_6_repeatreward: "5-xp,8-bottle o' enchanting"
- 3_6_item: "bottle o' enchanting"
- 3_6_repeat: true
- 3_6_repeatsperday: 15

- 3_7_needed: "32-diamond"
- 3_7_reward: "250-xp,1-lava bucket"
- 3_7_repeatreward: "150-xp,1-lava bucket"
- 3_7_item: "lava bucket"
- 3_7_repeat: true
- 3_7_repeatsperday: 2

- 3_8_needed: "128-arrow"
- 3_8_reward: "125-xp,32-bone block"
- 3_8_repeatreward: "15-xp,16-bone block"
- 3_8_item: "bone block"
- 3_8_repeat: true
- 3_8_repeatsperday: 5

- 3_9_needed: "128-stick"
- 3_9_reward: "250-xp,16-bamboo plant"
- 3_9_repeatreward: "2-xp,2-bamboo plant"
- 3_9_item: "bamboo plant"
- 3_9_repeat: true
- 3_9_repeatsperday: 5

- 4_1_needed: "512-gold ingot"
- 4_1_reward: "150-xp,4-blaze rod"
- 4_1_repeatreward: "25-xp,1-blaze rod"
- 4_1_item: "blaze rod"
- 4_1_repeat: true
- 4_1_repeatsperday: 5
  
- 4_2_needed: "1-saddle,64-vertical hay bale,32-apple,64-carrot item"
- 4_2_reward: "25-xp,1-horse spawn egg,1-iron horse armor,1-leash,1-nametag"
- 4_2_repeatreward: "15-xp,1-horse spawn egg,1-leash,1-nametag"
- 4_2_item: "saddle"
- 4_2_repeat: true
- 4_2_repeatsperday: 5
  
- 4_3_needed: "128-glass"
- 4_3_reward: "150-xp,8-dirt"
- 4_3_repeatreward: "25-xp,2-dirt"
- 4_3_item: "dirt"
- 4_3_repeat: true
- 4_3_repeatsperday: 5
  
- 4_4_needed: "128-dried kelp"
- 4_4_reward: "30-xp,5-ink sac"
- 4_4_repeatreward: "5-xp,3-ink sac"
- 4_4_item: "ink sac"
- 4_4_repeat: true
- 4_4_repeatsperday: 5
  
- 4_5_needed: "4-awkward potion,64-ender pearl"
- 4_5_reward: "75-xp,2-chorus flower,18-end stone"
- 4_5_repeatreward: "10-xp,1-chorus flower,9-end stone"
- 4_5_item: "chorus flower"
- 4_5_repeat: true
- 4_5_repeatsperday: 5
  
- 4_6_needed: "4-gold sword,64-arrow,1-bow,1-water bucket"
- 4_6_reward: "75-xp,1-ghast tear,1-bucket"
- 4_6_repeatreward: "10-xp,1-ghast tear,1-bucket"
- 4_6_item: "ghast tear"
- 4_6_repeat: true
- 4_6_repeatsperday: 5

- 4_7_needed: "1728-rail,192-powered rail,64-detector rail,64-activator rail"
- 4_7_reward: "400-xp,1-elytra"
- 4_7_repeatreward: "200-xp,1-elytra"
- 4_7_item: "elytra"
- 4_7_repeat: true
- 4_7_repeatsperday: 5

- 4_8_needed: "64-sand,2-oak boat"
- 4_8_reward: "50-xp,24-prismarine shards,24-prismarine crystals"
- 4_8_repeatreward: "25-xp,12-prismarine shards,12-prismarine crystals"
- 4_8_item: "prismarine crystals"
- 4_8_repeat: true
- 4_8_repeatsperday: 10

- 4_9_needed: "1-water bucket,640-white wool"
- 4_9_reward: "50-xp,2-sponge"
- 4_9_repeatreward: "25-xp,1-sponge"
- 4_9_item: "sponge"
- 4_9_repeat: true
- 4_9_repeatsperday: 5

- 5_1_needed: "1728-rotten flesh"
- 5_1_reward: "150-xp,1-zombie head,3-diamond ore"
- 5_1_repeatreward: "50-xp,1-zombie head"
- 5_1_item: "zombie head"
- 5_1_repeat: true
- 5_1_repeatsperday: 5

- 5_2_needed: "1728-bone"
- 5_2_reward: "150-xp,1-skeleton head,3-diamond ore"
- 5_2_repeatreward: "50-xp,1-skeleton head"
- 5_2_item: "skeleton head"
- 5_2_repeat: true
- 5_2_repeatsperday: 5

- 5_3_needed: "1728-gunpowder"
- 5_3_reward: "150-xp,1-creeper head,3-diamond ore"
- 5_3_repeatreward: "50-xp,1-creeper head"
- 5_3_item: "creeper head"
- 5_3_repeat: true
- 5_3_repeatsperday: 5
  
- 5_4_needed: "576-leather,576-bone,576-rotten flesh,576-gunpowder"
- 5_4_reward: "150-xp,1-player head,3-diamond ore"
- 5_4_repeatreward: "50-xp,1-player head"
- 5_4_item: "player head"
- 5_4_repeat: true
- 5_4_repeatsperday: 5
  
- 5_5_needed: "64-living tube coral block,64-living brain coral block,64-living bubble coral block,64-living fire coral block,64-living horn coral block"
- 5_5_reward: "150-xp,2-dolphin spawn egg,2-turtle egg,4-nametag"
- 5_5_repeatreward: "10-xp,1-dolphin spawn egg,1-turtle egg,2-nametag"
- 5_5_item: "turtle egg"
- 5_5_repeat: true
- 5_5_repeatsperday: 5
  
- 5_6_needed: "128-iron block,64-emerald block,32-diamond block"
- 5_6_reward: "700-xp,1-villager spawn egg,1-nametag"
- 5_6_repeatreward: "400-xp,1-villager spawn egg,1-nametag"
- 5_6_item: "villager spawn egg"
- 5_6_repeat: true
- 5_6_repeatsperday: 2
  
- 5_7_needed: "2-zombie head,2-skeleton head,7-creeper head,7-player head"
- 5_7_reward: "2500-xp,1-dragon head"
- 5_7_repeatreward: "500-xp,1-dragon head"
- 5_7_item: "dragon head"
- 5_7_repeat: true
- 5_7_repeatsperday: 1

- 5_8_needed: "96-string"
- 5_8_reward: "25-xp,1-cobweb"
- 5_8_repeatreward: "5-xp,1-cobweb"
- 5_8_item: "cobweb"
- 5_8_repeat: true
- 5_8_repeatsperday: 10

- 5_9_needed: "64-spider eye"
- 5_9_reward: "10-xp,32-rotten flesh"
- 5_9_repeatreward: "2-xp,32-rotten flesh"
- 5_9_item: "rotten flesh"
- 5_9_repeat: true
- 5_9_repeatsperday: 25
